### ISSUE TITLE
Missing spirit ashes

### ISSUE THREAD

**Issue by daviegeepers** [RoundtableHold/roundtablehold.github.io#117]
Lhutel the headless
Stormhawk deenh
Raya lucaria soldier
Godrick soldier
Twinsage sorcerer
Glintstone sorcerer
Marionette soldier
Soldjar of fortune
Jellyfish
Land squirt
Albinauric
Wandering Noble
Noble sorcerer

I'm not clear how to add them so I'm submitting them. :)

**Comment by tmercswims** [comment]
I just checked for myself, and all the ashes you listed are indeed in the checklist. Might you have them checked, and then have "hide completed" toggled on so they don't show for you?

**Comment by daviegeepers** [comment]
Maybe it’s how I was using the search box. Sometimes things didn’t appear. I don’t know. Sorry. :)

Is there a possibility of alphabetizing the lists? May not because the way the data is stored?

**Comment by azy2** [comment]
Sorting pages is still on the table but it's trickier than it sounds. I'm working on it.
