### ISSUE TITLE
Axes

### ISSUE THREAD

**Issue by wdya** [RoundtableHold/roundtablehold.github.io#127]

**Comment by dcooke13** [comment]
Missing: Sacred Butchering Knife (https://eldenring.wiki.fextralife.com/Butchering+Knife)

Maybe it's just "Butchering Knife", but I haven't modded the one I got and it's Sacred so not sure.

**Comment by azy2** [comment]
That’s the affinity. It can be changed at a site of grace in the Ashe’s of war menu. See here https://eldenring.wiki.fextralife.com/Affinities
