### ISSUE TITLE
Bug with linked boxes

### ISSUE THREAD

**Issue by Zallar** [RoundtableHold/roundtablehold.github.io#128]
I have noticed that some boxes are linked. For example checking the checkbox for killing Battlemage Hueges will also check the box for the reward gotten (Battlemage Hueges Ashes). This is great, however whenever a reward is listed that is not garantued the linking of these things become problematic.

**Issue:**
The example I have found is the Cleanrot Knight in Stillwater Cave. If I check the box for killing this knight, the box for Cleanrot Knight's Sword is also checked. This item is dropped from Cleanrot Knights but it is not garantued. This means that there is no way to check the box for the boss without checking the box for the sword, even if the sword did not drop.

**Suggestion:**
Do not list/link (I am unaware of how the linking is done) items that are not a 100% drop from bosses as a reward from the boss.

This sword is the only one I have found so far but if the linking is done by name basis (it seems like it is?) this could be an issue for other items that are not garantued drops.

P.S. Really good job with the site. Keep up the good work! :)

**Comment by azy2** [comment]
Thanks for bringing this to my attention. I've gone ahead and fixed this one so you should be able to uncheck the sword now.
