### ISSUE TITLE
Quest checklist reset constantly on F5 or broswer re-open

### ISSUE THREAD

**Issue by chriscarollo** [RoundtableHold/roundtablehold.github.io#130]
Is there something I'm doing wrong?  I've been tracking all my questlines, and have even been exporting my state to a file to have a hard backup, and just now I F5ed the "NPC Questlines" page and I'm back at 0/238.

**Comment by azy2** [comment]
Hi, what OS and browser are you using? The site saves your data using cookies. You browser may be clearing them automatically. Check in settings if you have cookies enabled. In Chrome check that settings -> Privacy and Security -> Block third-party cookies in incognito is set. In Firefox make sure settings -> privacy and security -> delete cookies and site data when firefox is closed is unchecked.

**Comment by chriscarollo** [comment]
I'm using Brave, but don't have any cookie restrictions or clearing that's happening.

It actually looks like it uses localstorage, not cookies?  I'm seeing a bunch of strings in jStorage/__jstorage_meta/darksouls3_profiles/Default Profile/checklistData

Is it maybe due to having it open in multiple tabs?

**Comment by azy2** [comment]
Is the data in localstorage being cleared after a refresh or does the data persist and the site just shows nothing?

**Comment by chriscarollo** [comment]
I'll see if/when it happens again, if something is nuking that localstorage.

**Comment by azy2** [comment]
@chriscarollo is this still an issue?

**Comment by chriscarollo** [comment]
I haven't had it happen again since, but I also stopped having the site open in multiple tabs at once, so maybe something about that was stomping/clearing something?

Anyways, so far so good lately.  Really a great site for tracking progress, thanks!

**Comment by azy2** [comment]
I recently discovered a bug with multiple tabs which I think might have caused this. If you check some boxes in 1 tab, switch tabs and check some boxes in the 2nd tab, you'll lose the first tab's checks. Does this sound like what was happening? It should be fixed now.

**Comment by chriscarollo** [comment]
Oh yes, that definitely sounds like it could have been it.  Thanks, good to know it's fixed now!
