### ISSUE TITLE
Add a column to the weapons table for upgrade material

### ISSUE THREAD

**Issue by azy2** [RoundtableHold/roundtablehold.github.io#140]
Add a column called "Upgrade Material" and for each weapon put exactly "Normal" or "Somber" so that people can filter the page using the search box.

**Comment by ATH42** [comment]
I'm on it.

**Comment by ATH42** [comment]
issue is resolved with following [commits](https://github.com/RoundtableHold/roundtablehold.github.io/pull/162/commits)
