### ISSUE TITLE
Missing NPC questlines

### ISSUE THREAD

**Issue by wdya** [RoundtableHold/roundtablehold.github.io#15]
These NPCs still need their questlines written up:

- [x] Diallos
- [x] Millicent
- [x] Gowry
- [x] Alexander
- [x] Jar-Bairn
- [x] Bernahl
- [x] Blaidd
- [x] Ranni
- [x] Rya
- [x] Shabriri
- [x] Tanith
- [x] Three Fingers?
- [ ] more?

This is what I'm working on at the moment. Drop a comment here if you notice the list is missing anyone.

**Comment by Quivorian** [comment]
@wdya Are you basing these on Athrek's guides?

**Comment by JohannaB253** [comment]
Looks like these are all in other guides. Could maybe incorporate them as another option under Guides?

Ranni, and Blaidd - [Guide to the Age of Stars/Age of Duskborne Questline](https://www.reddit.com/r/Roundtable_Guides/comments/tipkvt/guide_to_the_age_of_starsage_of_duskborne/)

Bernahl, Diallos, Tanith and Rya - [Guide to the Volcano Manor Questline](https://www.reddit.com/r/Roundtable_Guides/comments/tiplfx/guide_to_the_volcano_manor_questline/)

Shabriri, Gowry, and Millicent - [Guide to the Lord of Frenzied Flame Questline](https://www.reddit.com/r/Roundtable_Guides/comments/tipm3z/guide_to_the_lord_of_the_frenzied_flame_questline/)

Alexander, Diallos, Jar-Bairn - [Guide to the Fixed Questlines AKA the Jarburg and Lord of Stormveil Questlines](https://www.reddit.com/r/Roundtable_Guides/comments/tipg8w/guide_to_the_fixed_questlines_aka_the_jarburg/)

**Comment by wdya** [comment]
> @wdya Are you basing these on Athrek's guides?

I've been using the wiki to write them from scratch. Hadn't seen these guides before, but they're fantastic.
