### ISSUE TITLE
Link items in Guides > Legendaries to associated Equipment list

### ISSUE THREAD

**Issue by dcooke13** [RoundtableHold/roundtablehold.github.io#187]
Did not test with all legendary items, but of the Talismans, only Godrey Icon seems properly linked with the corresponding item in the Equipment > Talismans page. Issue may or may not also apply to weapons/sorceries/incantations. 

Could also consider linking with the achievement -- currently checking off all 8 legendary talismans in the Guides > Legendaries list does not auto-complete the Legendary Talismans Achievement.

**Comment by azy2** [comment]
Item linking is currently a work in progress. We have not finished it so anything that's missing we likely know about but just haven't gotten around to it yet. If you have time to help hop in the dev discord and let's chat. You don't have to know how to code at all.
