### ISSUE TITLE
Can't create profiles and progress is not saving

### ISSUE THREAD

**Issue by sonnekonige** [RoundtableHold/roundtablehold.github.io#194]
Can't seem to be able to create a profile (click add, write the name, click add again, the profile is not on the list).
If I use the checklists, the number next to the titles doesn't increment, and also if I exit and enter again, no progress is saved.
I've tried the android app, google chrome on android and mozilla firefox on pc. Same issue across all platforms.

**Comment by azy2** [comment]
Thanks for the report. I messed up last night, it should be fixed now.
