### ISSUE TITLE
Leyndell Capital of Ash Graces

### ISSUE THREAD

**Issue by Summoner000** [RoundtableHold/roundtablehold.github.io#208]
Gonna do all the coordinates for the Ashen Capital graces. Although, I'm not 100% how this is going to work on the map, because isn't the Capital of Ash a completely different place? Won't it just put the grace locations on top of the Royal Capital map???

**Comment by azy2** [comment]
Issues shouldn't be closed until your contribution is back on the main repo where everyone can see it. When you are awake you'll need to make a pull request for all the changes you made.

**Comment by Summoner000** [comment]
Ok I didn't know that, and I guess I missed a step. Now I know!

**Comment by Summoner000** [comment]
I guess it's good to close now that I see them on the map and everything.
