### ISSUE TITLE
Lost all my clicks

### ISSUE THREAD

**Issue by daviegeepers** [RoundtableHold/roundtablehold.github.io#256]
Hi. All my clicks disappeared. I have the iOS app and web version on my phone and would sometimes use one or the other. 

They were there 2 days ago but gone last night. Any advice?

**Comment by azy2** [comment]
Did you clear your browsing history or delete any cookies? Or did you mess around with anything on the options page?

**Comment by daviegeepers** [comment]
I have not cleared my cache, and have not been to the options page.

**Comment by azy2** [comment]
Can you go to the options page and click export to clipboard and paste it here?

**Comment by daviegeepers** [comment]
Web:

{"current":"Default Profile","darksouls3_profiles":{"Default Profile":{"checklistData":{},"collapsed":{},"hide_completed":false,"journey":1,"style":"Standard","map_settings":{}}}}

iOS:

{"current":"Default Profile","darksouls3_profiles":{"Default Profile":{"checklistData":{},"collapsed":{},"hide_completed":false,"journey":1,"style":"Standard","map_settings":{}},"Dave":{"checklistData":{},"collapsed":{},"hide_completed":false,"journey":1,"style":"Standard"}}}

**Comment by azy2** [comment]
Unfortunately all your data is gone. There’s going to be no way for me to recover it. The site hasn’t changed in a few days and I haven’t seen anyone else complain about this so I can’t really say why this happened. Maybe your phone is setup to auto delete data after a set amount of time? I’m sorry.

**Comment by daviegeepers** [comment]
It's cool. Maybe a "backup" button that auto opens an email to send to yourself. Or auto upload to iCloud? Or write the file to another location?

**Comment by daviegeepers** [comment]
BTW - your stuff is so great. I'm disappointed but still happy I can use the app anyway. :)

**Comment by azy2** [comment]
You can save to file in the options page or save to clipboard. I want to automatically back things up for people but since it’s a website I don’t have permission to create files on your computer without user input so all I can do is provide backup buttons. Sorry again.
