### ISSUE TITLE
Add a Stonesword Keys page

### ISSUE THREAD

**Issue by azy2** [RoundtableHold/roundtablehold.github.io#258]
Requested by Astrelle in the discord

**Comment by wdya** [comment]
I'm putting Imp Statue Doors on it as well

**Comment by wdya** [comment]
Progress: 46/82 keys listed and mapped, 34/34 imp doors listed. ETA Saturday

**Comment by wdya** [comment]
Progress: 82/82 keys listed, 34/34 doors listed, 62/82 keys mapped. Should be done mapping keys late tonight and I'll make a pull request then, and add the imp door map locations this week
