### ISSUE TITLE
Unmarked Boss in Siofra 

### ISSUE THREAD

**Issue by Itsbenderintime** [RoundtableHold/roundtablehold.github.io#260]
Found a Dragonkin Soldier here https://imgur.com/a/MqepyYm

He dropped a Dragon Halberd https://eldenring.wiki.fextralife.com/Dragon+Halberd

**Comment by wdya** [comment]
This boss is listed. It's the first of two under Siofra River. It's not on our map yet, but the map is still a work in progress and most bosses past Caelid aren't mapped yet.

![Screenshot_20220616-144303_Elden Ring Guides.png](https://user-images.githubusercontent.com/21043502/174160278-af1dbf1a-1a37-438e-86e2-174feee8b6da.png)
