### ISSUE TITLE
W3C Validator Errors

### ISSUE THREAD

**Issue by ZKjellberg** [RoundtableHold/roundtablehold.github.io#28]
Working to address errors reported by the [W3C Checker](https://validator.w3.org/nu/?doc=https%3A%2F%2Froundtable-hold.github.io%2Ftracker%2F)

Errors:

- [ ] _Element [div](https://html.spec.whatwg.org/multipage/#the-div-element) is missing one or more of the following attributes: role._ (**192**) - Unknown what role to add. `type=button` is not appropriate as it triggers many further errors. [Line 147 of generate.py](https://github.com/Roundtable-Hold/tracker/blob/main/generate.py#L147)
- [ ] Element [ul](https://html.spec.whatwg.org/multipage/#the-ul-element) not allowed as child of element [ul](https://html.spec.whatwg.org/multipage/#the-ul-element) in this context. (**13**)
- [ ] `th` start tag in table body. (**94**)
- [x] ~~**Line 17540:** Attribute for_ not allowed on element [label](https://html.spec.whatwg.org/multipage/#the-label-element) at this point.~~
- [ ] **Line 17560:** Duplicate ID `profileModalTitle`.

Warnings (2)

- [x] ~~_This document appears to be written in English. Consider adding `lang="en"` (or variant) to the html start tag._ - Need to investigate where to add this.~~

PR #27 addressed the initial findings.

**Comment by azy2** [comment]
> Line 17540: Attribute for_ not allowed on element [label](https://html.spec.whatwg.org/multipage/#the-label-element) at this point.

He oops. The appropriate function in python is _for, not for_. That's where that is coming from. Python and HTML share some reserved keywords like for and input
