### ISSUE TITLE
Check off multiple boxes with one click

### ISSUE THREAD

**Issue by daviegeepers** [RoundtableHold/roundtablehold.github.io#85]
Hi. It may be cool to have other boxes check associated with a quest or item. Ex: You click off Super Weapon and the associated quest, location, boss, etc. turns off as well. It kinda sounds like a lot. I love this thing! So helpful. :)

**Comment by azy2** [comment]
That's in the works! It's a lot of work to find everything that needs to be linked together so no promises on when it will be ready, though.
